import Foundation

/// Builds the user-turn prompt shared by both Smart Capture services
/// (Foundation Models on-device and Gemini online). Centralizing the prompt
/// here keeps the two backends in lockstep so a plan generated by Gemini
/// after a network failure can be refined on-device without the LLM seeing a
/// different shape of context.
///
/// The prompt is structured into named sections (date, projects, project
/// context, recent tasks, open tasks, clarification, plan refinement) so the
/// LLM can ignore sections that aren't relevant to the current input.
/// A one-shot correction passed back into the prompt when post-validation
/// detected that the LLM dropped one or more extracted planning targets.
/// Lives outside `SmartCaptureContext` because it's specific to retry attempts.
struct PlanningCorrection: Equatable {
    let missingTargets: [ExtractedPlanningTarget]
    /// Optional snapshot of the prior workspace so the LLM has the imperfect
    /// draft to start from rather than regenerating from scratch.
    let priorWorkspace: PlanningWorkspace?
}

enum SmartCapturePromptBuilder {

    static func userPrompt(
        for context: SmartCaptureContext,
        correction: PlanningCorrection? = nil
    ) -> String {
        var sections: [String] = []
        sections.append(inputSection(context))
        sections.append(planningDepthSection(context))
        sections.append(dateAndLocaleSection(context))
        if let block = timeSignalsSection(context)   { sections.append(block) }
        sections.append(projectsSection(context))
        if let block = projectContextSection(context) { sections.append(block) }
        if let block = recentTasksSection(context)    { sections.append(block) }
        if let block = openTasksSection(context)      { sections.append(block) }
        if let block = overdueSection(context)        { sections.append(block) }
        if let block = completedSection(context)      { sections.append(block) }
        if let block = skippedSection(context)        { sections.append(block) }
        if let block = clarificationSection(context)  { sections.append(block) }
        if let block = refinementSection(context)     { sections.append(block) }
        if let correction { sections.append(correctionSection(correction)) }
        sections.append("Return a structured decision following the schema. Never resolve dates yourself — preserve the user's original time expressions, but treat the pre-resolved time signals above as known planning slots.")
        return sections.joined(separator: "\n\n")
    }

    /// Returns the refinement history to attach to a newly-generated workspace.
    /// If the input context contains a refinement request, the previous
    /// history is carried forward and a new entry is appended using the
    /// model's `planChangeSummary` (or a placeholder if the model omitted one).
    /// When this is the first draft, returns an empty array.
    static func refinementHistory(
        from context: SmartCaptureContext,
        appending changeSummary: String?
    ) -> [PlanRefinementHistoryItem] {
        guard let refinement = context.planRefinement else { return [] }
        let appendedSummary = changeSummary?
            .trimmingCharacters(in: .whitespacesAndNewlines)
            .nilIfEmpty
            ?? "Revision applied."
        return refinement.history + [
            PlanRefinementHistoryItem(
                feedback: refinement.feedback,
                createdAt: context.currentDate,
                summaryOfChange: appendedSummary
            )
        ]
    }

    // MARK: - Correction prompt for retry

    /// Built when the LLM's first response dropped one or more extracted
    /// planning targets. Tells the model exactly which targets are missing
    /// and instructs it to regenerate without dropping them.
    private static func correctionSection(_ correction: PlanningCorrection) -> String {
        var lines: [String] = []
        lines.append("CORRECTION (your previous response dropped these targets)")
        for target in correction.missingTargets {
            let dueBit = target.dueTimeExpression?.nilIfEmpty.map { ", due \($0)" } ?? ""
            let spanBit = target.sourceTextSpan?.nilIfEmpty.map { " — from “\($0)”" } ?? ""
            lines.append("  - “\(target.title)”\(dueBit)\(spanBit)")
        }
        lines.append("")
        if let prior = correction.priorWorkspace {
            lines.append("Your previous workspace had only these targets:")
            for target in prior.targets {
                let due = target.dueTimeExpression?.nilIfEmpty.map { " (due \($0))" } ?? ""
                lines.append("  - \(target.title)\(due)")
            }
            lines.append("")
        }
        lines.append("Regenerate the workspace. Every extracted planning target above MUST appear as its own PlanningTarget. Do not merge them unless the user explicitly asked for one combined plan.")
        return lines.joined(separator: "\n")
    }

    // MARK: - Section builders

    private static func inputSection(_ context: SmartCaptureContext) -> String {
        "Input: \"\(context.rawInput)\""
    }

    /// The hard gate on how much structure the model may produce. Stage 1
    /// (the deterministic classifier) already decided this; the model must not
    /// exceed it. This is what stops the LLM from over-planning a simple
    /// capture into invented procedural steps.
    private static func planningDepthSection(_ context: SmartCaptureContext) -> String {
        // A refinement carries its own, more specific instructions later; don't
        // pin it to the original depth.
        if context.planRefinement != nil {
            return "PLANNING DEPTH: structured (the user is refining an existing plan — follow the refinement instructions below)."
        }
        switch context.planningDepth {
        case .none:
            return """
            PLANNING DEPTH: none.
            The user did NOT ask for a plan, breakdown, schedule, sequence, roadmap, or steps. \
            Create exactly ONE atomic task (or reminder) that preserves the user's original intent. \
            Do NOT generate a plan, phases, or subtasks. Do NOT invent procedural or interface steps \
            (e.g. "log in", "open the app", "search", "review") — capture the intent as the user stated it. \
            If the input is too vague to act on, ask ONE short clarifying question instead.
            """
        case .lightweight:
            return """
            PLANNING DEPTH: lightweight.
            This is a recurring behaviour / habit. Create exactly ONE recurring task that preserves the \
            user's intent, enriched only with metadata: cadence/recurrence, an estimated duration, a \
            project, and an optional one-line note. \
            Do NOT decompose it. Do NOT invent procedural or interface subtasks (e.g. "log in", "open app", \
            "search", "review"). One recurring task — nothing more.
            """
        case .structured:
            return """
            PLANNING DEPTH: structured.
            The user asked for structure (or the capture contains several distinct items). You MAY create \
            multiple top-level tasks and break them into subtasks where it genuinely helps. \
            Keep subtasks meaningful — never pad with obvious interface steps.
            \(contextGroundingInstruction)
            """
        case .deep:
            return """
            PLANNING DEPTH: deep.
            This intent is project-scale (or the user explicitly asked for a full plan). Produce a \
            multi-phase plan / workspace with phased targets and subtasks. Keep every step substantive.
            \(contextGroundingInstruction)
            """
        }
    }

    /// Appended to every planning (structured/deep) instruction so the model
    /// builds a plan that CONTINUES the user's real project rather than emitting
    /// a generic answer. The concrete project context, open/overdue/completed
    /// tasks, and deadlines are supplied in their own sections below.
    private static let contextGroundingInstruction = """
    BEFORE PLANNING, read and use the context provided below — the relevant project's known context \
    (goal, audience, deadline, constraints, preferences, notes), its existing open tasks, overdue work, \
    recently completed work, and any deadlines. Build the plan to CONTINUE that project: extend what is \
    already there, do NOT restate or duplicate tasks that already exist, reschedule overdue items rather \
    than recreating them, never re-add completed or intentionally skipped work, and respect existing \
    deadlines and the user's stated constraints. If little or no project context exists, plan from the \
    user's description but keep assumptions explicit. The plan should feel like the next step in an \
    ongoing project, not a fresh generic plan.
    """

    private static func dateAndLocaleSection(_ context: SmartCaptureContext) -> String {
        var calendar = Calendar(identifier: .gregorian)
        calendar.timeZone = context.timezone
        calendar.locale = context.locale

        let dateFmt = DateFormatter()
        dateFmt.timeZone = context.timezone
        dateFmt.locale = context.locale
        dateFmt.dateStyle = .full
        dateFmt.timeStyle = .none

        let timeFmt = DateFormatter()
        timeFmt.timeZone = context.timezone
        timeFmt.locale = context.locale
        timeFmt.dateFormat = "HH:mm"

        let weekdayIndex = calendar.component(.weekday, from: context.currentDate) - 1
        let weekday = (0..<calendar.weekdaySymbols.count).contains(weekdayIndex)
            ? calendar.weekdaySymbols[weekdayIndex]
            : "Unknown"

        return """
        Current date: \(dateFmt.string(from: context.currentDate)) (\(weekday))
        Current time: \(timeFmt.string(from: context.currentDate))
        Timezone: \(context.timezone.identifier)
        Locale: \(context.locale.identifier)
        """
    }

    private static func timeSignalsSection(_ context: SmartCaptureContext) -> String? {
        let signals = context.timeSignals
            .filter { $0.resolverPath != .noSignal && $0.confidence >= 0.70 }
        guard !signals.isEmpty else { return nil }

        let dateFmt = DateFormatter()
        dateFmt.timeZone = context.timezone
        dateFmt.locale = context.locale
        dateFmt.dateStyle = .medium
        dateFmt.timeStyle = .none

        let lines = signals.map { signal -> String in
            var pieces = [
                "  - raw: \"\(signal.rawText)\"",
                "type: \(signal.interpretation.rawValue)",
                "confidence: \(String(format: "%.2f", signal.confidence))",
                "path: \(signal.resolverPath.rawValue)"
            ]
            if let date = signal.resolvedDate {
                pieces.append("resolvedDate: \(dateFmt.string(from: date))")
            }
            if let duration = signal.resolvedDuration {
                let days = duration / 86_400
                pieces.append("durationDays: \(String(format: "%.1f", days))")
            }
            return pieces.joined(separator: ", ")
        }
        .joined(separator: "\n")

        return """
        Known time signals:
        \(lines)

        If these signals include a deadline, duration, or relative time window, the timeline is NOT missing. Do not ask for the timeline again. If clarification is still needed, ask about missing scope, deliverable, priority, constraints, or success criteria.
        """
    }

    private static func projectsSection(_ context: SmartCaptureContext) -> String {
        if context.activeProjects.isEmpty {
            return "Active projects: none"
        }
        let list = context.activeProjects
            .prefix(20)
            .map { "  - \($0.name) (\($0.activeItemCount) active)" }
            .joined(separator: "\n")
        var section = "Active projects:\n\(list)"
        if let selected = context.selectedProject {
            section += "\nSelected project: \(selected.name)"
        }
        return section
    }

    private static func projectContextSection(_ context: SmartCaptureContext) -> String? {
        let summaries = context.projectContextSummaries
        guard !summaries.isEmpty else { return nil }

        var blocks: [String] = ["Known project context:"]
        for summary in summaries.prefix(10) {
            var lines: [String] = ["  Project \"\(summary.projectName)\":"]
            if let goal = summary.goal?.nilIfEmpty {
                lines.append("    goal: \(goal)")
            }
            if let audience = summary.audience?.nilIfEmpty {
                lines.append("    audience: \(audience)")
            }
            if let deadline = summary.deadlineExpression?.nilIfEmpty {
                lines.append("    deadline: \(deadline)")
            }
            if !summary.keyReferences.isEmpty {
                lines.append("    references: \(joinedShort(summary.keyReferences))")
            }
            if !summary.constraints.isEmpty {
                lines.append("    constraints: \(joinedShort(summary.constraints))")
            }
            if !summary.successCriteria.isEmpty {
                lines.append("    success: \(joinedShort(summary.successCriteria))")
            }
            if !summary.openQuestions.isEmpty {
                lines.append("    open questions: \(joinedShort(summary.openQuestions))")
            }
            if !summary.userPreferences.isEmpty {
                lines.append("    preferences: \(joinedShort(summary.userPreferences))")
            }
            if !summary.recentContextNotes.isEmpty {
                lines.append("    recent notes:")
                for note in summary.recentContextNotes.prefix(5) {
                    lines.append("      - \(truncate(note, max: 200))")
                }
            }
            // If only the header line, skip — no real context for this project.
            if lines.count > 1 { blocks.append(lines.joined(separator: "\n")) }
        }
        return blocks.count > 1 ? blocks.joined(separator: "\n") : nil
    }

    private static func recentTasksSection(_ context: SmartCaptureContext) -> String? {
        guard !context.recentTasks.isEmpty else { return nil }
        let rendered = context.recentTasks
            .prefix(10)
            .map { renderTask($0) }
            .joined(separator: "\n")
        return "Recent tasks:\n\(rendered)"
    }

    private static func openTasksSection(_ context: SmartCaptureContext) -> String? {
        guard !context.openTasksForRelevantProject.isEmpty else { return nil }
        let rendered = context.openTasksForRelevantProject
            .prefix(8)
            .map { renderTask($0) }
            .joined(separator: "\n")
        return "Open tasks for the relevant project (avoid duplicating these):\n\(rendered)"
    }

    // Project history — what already happened, so plans respect it.

    private static func overdueSection(_ context: SmartCaptureContext) -> String? {
        guard !context.overdueTasks.isEmpty else { return nil }
        let rendered = context.overdueTasks.prefix(8).map { renderTask($0) }.joined(separator: "\n")
        return "Overdue work (already on the timeline — reschedule rather than recreate):\n\(rendered)"
    }

    private static func completedSection(_ context: SmartCaptureContext) -> String? {
        guard !context.recentlyCompletedTasks.isEmpty else { return nil }
        let rendered = context.recentlyCompletedTasks.prefix(8).map { renderTask($0) }.joined(separator: "\n")
        return "Recently completed (done — do not re-plan these):\n\(rendered)"
    }

    private static func skippedSection(_ context: SmartCaptureContext) -> String? {
        guard !context.skippedTasks.isEmpty else { return nil }
        let rendered = context.skippedTasks.prefix(5).map { renderTask($0) }.joined(separator: "\n")
        return "Intentionally skipped (the user chose not to do these — don't reintroduce them):\n\(rendered)"
    }

    private static func clarificationSection(_ context: SmartCaptureContext) -> String? {
        guard let c = context.clarificationState else { return nil }
        return """
        Previous clarification:
          original input: \"\(c.previousInput)\"
          question: \(c.previousQuestion.question)
          user answered: \(c.userAnswer)

        Continue the same capture. Use the answer semantically, then either ask the next necessary question or produce the appropriate task/plan preview. Never stop after recording the answer.
        """
    }

    private static func refinementSection(_ context: SmartCaptureContext) -> String? {
        guard let r = context.planRefinement else { return nil }
        let workspace = r.previousWorkspace

        var lines: [String] = []
        lines.append("PLAN REFINEMENT")
        lines.append("Original input: \"\(r.originalInput)\"")
        lines.append("User feedback for this revision: \"\(r.feedback)\"")
        lines.append("")
        lines.append("Previous workspace:")
        lines.append("  title: \(workspace.title)")
        if let scope = workspace.estimatedScope?.nilIfEmpty {
            lines.append("  scope: \(scope)")
        }
        if let summary = workspace.summary?.nilIfEmpty {
            lines.append("  summary: \(summary)")
        }
        if !workspace.assumptions.isEmpty {
            lines.append("  assumptions: \(joinedShort(workspace.assumptions))")
        }
        lines.append("  detected target count: \(workspace.detectedTargetCount), actual: \(workspace.targets.count)")

        for (targetIdx, target) in workspace.targets.prefix(8).enumerated() {
            var header = "  Target \(targetIdx + 1): \"\(target.title)\""
            if let due = target.dueTimeExpression?.nilIfEmpty {
                header += " — due \(due)"
            }
            if target.status != .ready {
                header += " [\(target.status.rawValue)]"
            }
            lines.append(header)
            if let project = target.projectName?.nilIfEmpty {
                lines.append("    project: \(project)")
            }
            if let span = target.sourceTextSpan?.nilIfEmpty {
                lines.append("    from: \"\(span)\"")
            }
            for (phaseIdx, phase) in target.phases.prefix(5).enumerated() {
                lines.append("    Phase \(phaseIdx + 1): \(phase.title) — \(phase.purpose)")
                if let timing = phase.phaseTimeExpression?.nilIfEmpty {
                    lines.append("      timing: \(timing)")
                }
                for task in phase.tasks.prefix(5) {
                    let timing = task.timeExpression?.nilIfEmpty.map { " (\($0))" } ?? ""
                    lines.append("      - \(task.title)\(timing)")
                }
            }
        }

        if !r.history.isEmpty {
            lines.append("")
            lines.append("Earlier refinements:")
            for (idx, item) in r.history.suffix(5).enumerated() {
                lines.append("  \(idx + 1). \"\(item.feedback)\" → \(item.summaryOfChange)")
            }
        }

        lines.append("")
        lines.append("Revise the workspace above to address the feedback. Treat the feedback as a planning command or constraint, not as a new raw task. Set planChangeSummary to one sentence describing what changed. Preserve all existing PlanningTargets unless the user asked to remove or merge them — if the user says a target was missed, ADD it as a new target. If they say split, separate by deliverable/deadline. If they say merge, combine into one schedule but keep target metadata visible.")
        return lines.joined(separator: "\n")
    }

    // MARK: - Helpers

    private static func renderTask(_ task: TaskSummary) -> String {
        let project = task.projectName?.nilIfEmpty.map { " [\($0)]" } ?? ""
        let when: String = {
            if let due = task.dueDate {
                let fmt = DateFormatter()
                fmt.dateStyle = .medium
                fmt.timeStyle = .none
                return " · due \(fmt.string(from: due))"
            }
            if let expr = task.timeExpression?.nilIfEmpty {
                return " · \(expr)"
            }
            return ""
        }()
        return "  - \(task.title) (\(task.status))\(project)\(when)"
    }

    private static func joinedShort(_ items: [String]) -> String {
        items.prefix(6).map { truncate($0, max: 80) }.joined(separator: "; ")
    }

    private static func truncate(_ string: String, max: Int) -> String {
        let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.count > max else { return trimmed }
        let end = trimmed.index(trimmed.startIndex, offsetBy: max)
        return String(trimmed[..<end]) + "…"
    }
}

// MARK: - Tiny string helper

extension String {
    /// Returns `nil` when the trimmed string is empty, otherwise the trimmed
    /// value. Used across Smart Capture for "treat blank user input as
    /// missing" semantics.
    var nilIfEmpty: String? {
        let trimmed = trimmingCharacters(in: .whitespacesAndNewlines)
        return trimmed.isEmpty ? nil : trimmed
    }
}
