name: Moti
options:
  bundleIdPrefix: com.malik
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_VERSION: "5.0"
    SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
targets:
  Moti:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Moti
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.malik.Moti
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
